apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: java-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
